### ISSUE TITLE
Embedding on OCP

### ISSUE THREAD

**Issue by micuentadecasa** [eartvit/llm-on-ocp#1]
Hi, I would like to get a yaml file for embedding in OCP, I only see examples of inference, but no yaml file for embedding.

Regards.

**Comment by eartvit** [comment]
Hi, I am not sure I understand, what do you mean to embed in OCP? Can you please elaborate? 

If you meant the LLM, it runs inside OCP (OpenShift cluster) deployed via the RHOAI (Red Hat OpenShift AI) Operator. That is the recommended way from RedHat. The deployment is created inside the vLLM container (or Ollama one) that exposes an endpoint to access the LLM, hence the inference from an application that may want to use it. You can use the upstream version, ODH, if you don't want to use RHOAI (and then you have ODH community support). It's possible to deploy just with KServe too, but that is not supported - you may still get help from the community though. However, if you want to have your chatbot and LLM inside the same container, that is not recommended practice.

In any case, please elaborate what you are looking for so that I can see how I can help you.

Best regards,
Arthur

**Comment by micuentadecasa** [comment]
Hi @eartvit thanks for your message, I'm deploying the Kotaemon solution, an open source RAG in OCP, and I have Mistral in another Pod for inferencing, and I miss another Pod for embedding.

 I'm new in OCP, a guy from Red Hat mounted the mistral 7B in my environment with an UBI image with VLLM for inferencing, and now I want to create an embedding instance in the same way, but I don't know how to do it, I will appreciate if you can give me some instructions, what parameters I have to use for embedding?, I suppose they are different from the inference one.

**Comment by eartvit** [comment]
Hi, I am not familiar with the Kotaemon solution, however if it's a RAG then I guess it is similar with what I show in this repo. Typically you have 4 components in a RAG solution: 1st is the LLM that will use the RAG datasource to generate responses, the 2nd is the RAG database itself, the 3rd is the RAG ingestion component and the 4th one is the chatbot or application that uses the LLM endpoint and the RAG backend (endpoint) to obtain something from the RAG database. As mentioned earlier, please do not try to put everything in one deployment, keep them separate, that is the recommended (best) practice. All 4 components I mentioned should run in separate pods as they serve separate functions.

If, on the other hand, by embedding instance you mean the RAG ingestion process, in other words, create embeddings from a list of documents to store them in the RAG database instance (in my demo this is Milvus database), then I've already shared in this repo in the notebooks section a Jupyter notebook on how to achieve this. You can follow that to adapt to what Kotaemon is using and you can do it either through Jupyter notebook as I did, or write an app and deploy it on OpenShift. OpenShift has a feature called s2i (source to image) so if you don't know how to create a deployment and a container for your application, just write your application and put it in a git repo and then using the OpenShift console, in the developer view, use the function to deploy something directly from git. OpenShift will create the process to deploy that code in a container.

I hope this clarifies things.

BR,
Arthur

**Comment by micuentadecasa** [comment]
hi @eartvit , I know the RAG systems, and I do plan to install everything separated in multiple pods, so far so good, the only part that I miss is a Pod with VLLM and a embedding model, so what I need is a manifest to deploy a VLLM image with the configuration to download the mistral 7B for embedding, and run it in embedding mode, not the inference one, I think I need some parameters in VLLM.

in your file llm-serving-runtime/vLLM.yaml there is  a yaml to deploy VLLM, but I don't see where do you specify the model and the parameters, and in the notebook you use the mnt/models generic, so there should be a generic model by default.

as I said before what I need is to use your yaml to deploy, but specifying the model and putting it in embedding mode.

**Comment by eartvit** [comment]
Hello, 

The vLLM.yaml is a generic way to declare the seving runtime inside RHOAI. The parameters are specified in there, at least the ones you want to specify. Since this is a template for creating several instances inside the OpenShift platform, the name of the model being deployed should not be provided among the parameters. I provided the bare minimum parameters I needed for this demo

The /mnt/models is the location from where the vLLM server will pick up the model files and load them in memory and then serve via an inference point it creates (as per the [vLLM-docs](https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html)). You can only load a model at a time, so you can specify this with the model name or by it's location. Since the vLLM is a serving template, it is preferable to use a location as this is more generic and would apply to any models you want to serve. The RHOAI user interface binds the data connection (where the model is located) with the KServe runtime where the vLLM instance will be running. The videos I shared in this demo walk you through this process and you will see that you can load any model you want. 

This will, however still expose an URL then you need to use (via inferencing). And btw, I am still confused on what you mean by running the model in embedding mode. To me this sounds like you want some API to load the model in that application and then proceed with some other application logic. If you want to do this then you can't use vLLM since that one runs as a standalone server process and it serves one model that is provided as parameter during startup. The vLLM client API is used to connect to the inference endpoint exposed by the vLLM server, from a different application. ([vLLM-docs](https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html)). I reiterate, if you watch the videos I shared with this repo you can see how to add a vLLM deployment to RHOAI and how to use it to deploy a model (like Mistral) which you need to download beforehand and add to some block storage (S3 compatible) that is used as a data connection by RHOAI.

If you want to start the server and then load different models then Ollama is the server that functions like this. This is also detailed in the videos I shared.

Then, for the embeddings model, also known as the tokenizer for the text you want to put in the vector store of your RAG database, the code I shared in the notebooks show how this is used (as a client application):
1. First, you have the ingestion/provisioning/encoding part into the DB

```# If you want to use a GPU, change the model_kwargs as below, otherwise leave it empty, as in the default setting
#model_kwargs = {'device': 'cuda'}
model_kwargs = {}
embeddings = HuggingFaceEmbeddings(
    model_kwargs=model_kwargs,
    show_progress=True
)

#BEWARE: 'drop_old' is set to True, so if the collection already existed it will deleted first.
db = Milvus(
    embedding_function=embeddings,
    connection_args={"host": MILVUS_HOST, "port": MILVUS_PORT, "user": MILVUS_USERNAME, "password": MILVUS_PASSWORD},
    collection_name=MILVUS_COLLECTION,
    metadata_field="metadata",
    text_field="page_content",
    auto_id=True,
    drop_old=True
    )
```

2. Then you have the application that binds it together (different app, different notebook)

```
#This is how you setup the same function you used earlier for DB provisioning. Mind the same model is in both cases
model_kwargs = {'trust_remote_code': True}
embeddings = HuggingFaceEmbeddings(
    #model_name="nomic-ai/nomic-embed-text-v1",
    model_kwargs=model_kwargs,
    show_progress=False
)

#declare the store connection to your RAG database instance
store = Milvus(
    embedding_function=embeddings,
    connection_args={"host": MILVUS_HOST, "port": MILVUS_PORT, "user": MILVUS_USERNAME, "password": MILVUS_PASSWORD},
    collection_name=MILVUS_COLLECTION,
    metadata_field="metadata",
    text_field="page_content",
    drop_old=False
    )

#instantiate the LLM by it's exposed inference URL
llm =  VLLMOpenAI(
    openai_api_key="EMPTY",
    openai_api_base=f"{INFERENCE_SERVER_URL}/v1",
    model_name=MODEL_NAME,
    max_tokens=MAX_TOKENS,
    top_p=TOP_P,
    temperature=TEMPERATURE,
    presence_penalty=PRESENCE_PENALTY,
    streaming=True,
    verbose=False,
    callbacks=[StreamingStdOutCallbackHandler()]
)

#create your chatbot instance
qa_chain = RetrievalQA.from_chain_type(
        llm,
        retriever=store.as_retriever(
            search_type="similarity",
            search_kwargs={"k": 4}
            ),
        chain_type_kwargs={"prompt": QA_CHAIN_PROMPT},
        return_source_documents=True
        )

#then ask it a question.
question = "How can I create a Data Science Project?"
result = qa_chain.invoke({"query": question})
```

Once again, these are all in the notebooks I shared and explained in the videos associated with this guide.
I hope this makes things clearer.

BR,
Arthur

**Comment by micuentadecasa** [comment]
In the 0.4.3 versión of vllm there are two models for embedding gemma2 and
mistral, and the parameter task=embedding,  so there is no need to do it
programátically in the code, it can be done vía api.

**Comment by eartvit** [comment]
I am looking at the latest documentation on the [vLLM server](https://docs.vllm.ai/en/stable/models/engine_args.html) and there is no such parameter listed on the engine (server) side. 
Also, can you please provide the source of your information for your claim. I did a very brief search in the vLLM docs and I could not find anything.

**Comment by eartvit** [comment]
I think I found it: your [embedding](https://docs.vllm.ai/en/latest/models/supported_models.html) refers to using an embedding model (like e5-mistral-7b-instruct), not a generation one. Well, in that case you need add in the yaml another 2 lines for that parameter, something like below: 
```
  containers:
    - args:
        - --model
        - /mnt/models/
        - --dtype
        - float16
        - --max-model-len
        - "5900"
        - --download-dir
        - /models-cache
        - --port
        - "8080"
        - --task
        - "embedding"
```

Be advised that in this case you would be able to use this particular template only for the purpose of deploying a supported embedding model.
Probably you would also need a different template for a generic model too, so you would have 2 different vLLM serving runtime instances in your deployment, both controlled via RHOAI operator.

I think this concludes your search...

**Comment by micuentadecasa** [comment]
I think that will work, and yes people from vllm told me that I need two
pods

**Comment by eartvit** [comment]
Okay, thanks for the confirmation. I will close the issue then as solved
